# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=9)),
                ('voronoi', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AntIndic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('antena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Antena')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=9)),
                ('zoom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CiudIndic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residentesTotal', models.IntegerField()),
                ('movimientoTotal', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Desplazamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50)),
                ('hora', models.IntegerField()),
                ('personasTotal', models.IntegerField()),
                ('movimientoTotal', models.IntegerField()),
                ('suma', models.IntegerField()),
                ('mediana', models.IntegerField()),
                ('moda', models.IntegerField()),
                ('promedio', models.IntegerField()),
                ('desviacionSt', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
                ('varianza', models.IntegerField()),
                ('p25', models.IntegerField()),
                ('p50', models.IntegerField()),
                ('p75', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numa', models.CharField(max_length=50)),
                ('horai', models.IntegerField()),
                ('horaf', models.IntegerField()),
                ('dia', models.CharField(max_length=50)),
                ('antena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Antena')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='desplazamiento',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Indicador'),
        ),
        migrations.AddField(
            model_name='ciudindic',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Indicador'),
        ),
        migrations.AddField(
            model_name='antindic',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Indicador'),
        ),
        migrations.AddField(
            model_name='antena',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayect.Ciudad'),
        ),
    ]
