# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-05 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trayect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antindic',
            name='nombre',
        ),
    ]
