# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayect', '0005_auto_20180126_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numa',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
