# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-29 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trayect', '0006_auto_20180126_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estadia',
            unique_together=set([('numa', 'horaP', 'dia')]),
        ),
    ]
