# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayect', '0007_auto_20180129_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antena',
            name='habitantesTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
