# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna_esc',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='comuna_esc',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='conurbacion_esc',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='conurbacion_esc',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
