# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-27 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalamiento', '0007_auto_20181026_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_mostrar', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('medida', models.CharField(blank=True, max_length=100, null=True)),
                ('toma_dato', models.CharField(blank=True, max_length=100, null=True)),
                ('regimen', models.CharField(blank=True, max_length=100, null=True)),
                ('a0b10', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('mb10', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('n_calculob10', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Arrested',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Birthrate',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Burglary',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_CO2_transport',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Cardiovascular',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Companies',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Crime',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Deaths',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Emergency',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Green',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Hospitalizations',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Iliteracy',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Income',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Indigenous',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Injuries',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Municipal_Power',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Municipal_Water',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Municipal_cleaning',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Municipal_spending',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Non_motorized',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Offence_Person',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Offence_Property',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Professionals',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Respiratory',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Robbery',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Sales',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Solid_waste',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Street',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Unemployment',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_University',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_Year_scholarship',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_motor',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_pob_Comun_2002',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_private_transport',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_public_transport',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_technicians',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_vehicle',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='comuna_esc',
            name='log_workers',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=35, null=True),
        ),
    ]
