# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-27 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalamiento', '0008_auto_20181227_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='fuente',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
